version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - cmake
    - libboost-all-dev
    - libeigen3-dev
  tools:
    python: "3.8"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
