"""first

Revision ID: 76f93ac60d65
Revises: 
Create Date: 2025-07-06 06:48:26.844382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f93ac60d65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('request_description', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('x_twitter', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=3), nullable=True),
    sa.Column('number_of_tweets', sa.String(length=30), nullable=True),
    sa.Column('number_of_posts', sa.String(length=30), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('result',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('generated_date', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('subresult',
    sa.Column('subresult_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.String(length=30), nullable=True),
    sa.Column('creation_date', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=3), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.String(length=30), nullable=False),
    sa.Column('user_creation_date', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('user_username', sa.String(length=100), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_follower_count', sa.Integer(), nullable=True),
    sa.Column('user_following_count', sa.Integer(), nullable=True),
    sa.Column('user_is_verified', sa.Boolean(), nullable=True),
    sa.Column('user_blue_is_verified', sa.Boolean(), nullable=True),
    sa.Column('user_location', sa.String(length=300), nullable=True),
    sa.Column('user_description', sa.String(length=300), nullable=True),
    sa.Column('user_number_of_tweets', sa.Integer(), nullable=True),
    sa.Column('user_bot', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['result.result_id'], ),
    sa.PrimaryKeyConstraint('subresult_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subresult')
    op.drop_table('result')
    op.drop_table('request')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
